### ISSUE TITLE
Bug: Wrong line number

### ISSUE THREAD

**Issue by EdenComp** [RezaRahemtola/epitech-norm-checker#2]
My file had two line breaks at the end (line 54 and 55).
It detected the coding style but line 1 was written instead of lines 54 / 55

Trace:
G9 - Leading/Trailing lines detected in ./src/string/my_strcat.c:1

**Comment by aazam-gh** [comment]
Hi, I'd like to work on this issue.

![g9](https://user-images.githubusercontent.com/59562284/163156624-aa0e5e3f-08d5-4b0e-a5c2-6c18db7e75a9.png)

Line hasnt been specified and instead only been given a value of 1. Hence it will result in the first line being displayed regardless of which line the trailing and leading spaces are

**Comment by RezaRahemtola** [comment]
> Hi, I'd like to work on this issue.
> 
> ![g9](https://user-images.githubusercontent.com/59562284/163156624-aa0e5e3f-08d5-4b0e-a5c2-6c18db7e75a9.png)
> 
> Line hasnt been specified and instead only been given a value of 1. Hence it will result in the first line being displayed regardless of which line the trailing and leading spaces are

Hi, thanks for your interest.
Indeed this is a very small project I'm doing when I have some free time, so contribution guidelines aren't yet set up.

Feel free to fork and make a pull request to set the real line number in this case and I will merge it.

**Comment by aazam-gh** [comment]
I've made a pull request, let me know if everything is upto your expectations. Thanks and have a good day!
